### ISSUE TITLE
bold font is ignored in banking & classical style.

### ISSUE THREAD

**Issue by SilasK** [moderncv/moderncv#102]
I want to use textbf to highligt different parts in the CV however this is ignored in the most recent version of Tex Live

This seems to be the case only for tex live distribution 2021 and not 2020.

**Comment by SilasK** [comment]
It seems when I change the default font. e.g. usepackage{palatino} the bold faces are also ignored.

**Comment by stephanlachnit** [comment]
Which version of moderncv do you use?

Versions prior to 2.2.0 had a buggy font loading procedure (probably why TeXLive 2020 works for you)
Version 2.2.0 corrected this code and set all fonts to Latin Modern (probably why TeXLive 2021 does not work for you)
Since Version 2.3.0 we removed the font loading entirely, so it's up to the user to do it.

Although you didn't provide a minimum working example, I suspect you set the fonts incorrectly. If you use LuaTeX or XeTeX (highly recommended), do it like in the template:

https://github.com/moderncv/moderncv/blob/a89a2a74552d9c39faf4c438da5ff6691c453494/template.tex#L31-L37

This should work with all versions.

**Comment by SilasK** [comment]
Thank you!

**Comment by RakeshJarupula** [comment]
It works thank you :)

**Comment by FranklinYu** [comment]
For me the only required line seems to be loading the `fontspec` package. I guess it is because I only use the serif font (i.e. the “main” font).
