### ISSUE TITLE
No way to specify a subject line in the cover letter

### ISSUE THREAD

**Issue by jranke** [moderncv/moderncv#113]
I wonder if anyone is using the cover letter feature, as template.tex puts it after the CV, and I believe it should be before the CV in the PDF. This can easily be solved by moving things around (I can send a PR for the template.tex if you like).

But for me, it would be necessary to be able to specify a subject line. There are a couple of suggestions floating around, on [launchpad](https://answers.launchpad.net/moderncv/+question/222784) and [stackexchange](https://tex.stackexchange.com/questions/328056/add-the-field-subject-to-moderncv-letter). What do you think?

**Comment by mefuller** [comment]
I do use moderncv to make cover letters, but I usually have a separate file for my (generic) CV and for the letter alone.
I've actually never tried generating both from one tex file

Feel free to open a PR - I'm all for having an optional subject line, and placing the letter ahead of the CV is fine provided no letter is generated when undesired (no blank page)

**Comment by stephanlachnit** [comment]
> I wonder if anyone is using the cover letter feature, as template.tex puts it after the CV, and I believe it should be before the CV in the PDF. This can easily be solved by moving things around (I can send a PR for the template.tex if you like).

As you mentioned, one can just move the letter before the CV, no problem. I wouldn't do it in the template though since the main point of this package is the CV, no the cover letter, so that should be the first thing to see on the template. We could add a note that letter can also be moved before the CV.

> But for me, it would be necessary to be able to specify a subject line.

Sounds nice, but iirc moderncv uses the standard LaTeX letter class (http://mirrors.ibiblio.org/CTAN/macros/latex/base/letter.pdf), which doesn't have a subject option. I think it would be better to leave it at this base class and add a subject via the hacks you already discovered. If you any good (code) suggestions though, feel still free to open a PR to discuss it.

**Comment by jranke** [comment]
OK, I had only modified the moderncvhead file for one of the styles. Now I have added the optional subject to all header variants and rebased on current master.
