### ISSUE TITLE
Academicons warning

### ISSUE THREAD

**Issue by Thrashophil** [moderncv/moderncv#122]
I think moderncv should first check if the user is indeed using academicons and then output the warning if necessary.

**Comment by tianyizheng02** [comment]
@stephanlachnit May I ask why this isn't considered a bug? I believe Academicons requires either XeTeX or LuaTeX, so users who aren't using either of those engines will always get this warning.

**Comment by mefuller** [comment]
It's a warning that shows up in the log - for the user compiling with e.g. pdfLaTeX and not requiring academicons, it's just a note that will be there, but it won't affect the compiled CV.
I'd say it's "not a bug" since it doesn't impair functionality, but it's an "enhancement" since dropping an unnecessary warning would make the log that much more relevant.
Feel free to submit a PR to implement this change.
