### ISSUE TITLE
No page number displayed despite using option \nopagenumbers{}

### ISSUE THREAD

**Issue by fruehaufm** [moderncv/moderncv#145]
The option `"%\nopagenumbers{}                                  % uncomment to suppress automatic page numbering for CVs longer than one page"` in `template.tex` does not work.
No page numbers are displayed even if it is commented out.

See also https://github.com/xdanaux/moderncv/issues/70.

**Comment by mefuller** [comment]
The issue here is actually that the footer is overflowing the page and the page numbers are being cut off.
Please try adjusting the value or commenting out the footskip: `\setlength{\footskip}{149.60005pt}`

This issue has arisen in part due to the excessive number of social symbols that we attempt to display in the template file.

**Comment by fruehaufm** [comment]
Thank you for your feedback!
