### ISSUE TITLE
Setting length `\quotewidth` doesn't work

### ISSUE THREAD

**Issue by codecrusher64** [moderncv/moderncv#175]
When setting the length `\quotewidth` according to the documentation in section *"More customizations" > "Adjusting lengths"* with
```
\setlength{\quotewidth}{<width>}
```
nothing changes. I set this length in the preamble of my document.

I also recognized, that according to the documentation in section "In the preamble" `\recomputelengths` has to be added, when changing page layout lengths. I don't know if `\quotewidth` is a page layout length and added `\recomputelengths` after changing length `\quotewidth`, but again nothing changed. Finally I tried to change the length `\quotewidth` before loading the `geometry` package, but here `\quotewidth` is an undefined control sequence.

What's the correct way to change the length `\quotewidth`?

The only working solution currently is to renew command `\recomputecvheadlengths`. Having a look into the code, it seems that the `\quotewidth` is hardcoded inside this command for instance [here](https://github.com/moderncv/moderncv/blob/f3dd14ff621583bb6ce12d7e84a499f54cfa068f/moderncvheadi.sty#L64). And therefore this solution worked:
```
\renewcommand*{\recomputecvheadlengths}{%
  \setlength{\quotewidth}{<width>}}
```

**Specifications**
  - moderncv version: 2022-02-21 v2.3.1
  - LaTeX compiler: LuaHBTeX, Version 1.17.0 (TeXLive 2023)
  - Platform: Arch Linux

**Comment by LLdaniel** [comment]
Can confirm the described behaviour with the following specs:
* pdfTeX 3.141592653-2.6-1.40.24 
* TeX Live 2022/Debian (2022.20230122-3)

I think it is totally fine to use `\renewcommand` for re-defining a command. Further investigation is needed to analyze when the documented command did work or when it broke. 
Therefore I will label this issue as "documentation", "bug", because either we have to change the documentation or find a way to make the documented command work again.

**Comment by LLdaniel** [comment]
This is now documented within the new `moderncv_userguide.pdf`, see chapter 3.4 "Adjusting lengths".
