### ISSUE TITLE
Import of `fontenc` changes the behavior of `maketitle` command

### ISSUE THREAD

**Issue by EvilCheetah** [moderncv/moderncv#190]
**Describe the bug**
When using `\usepackage[T1]{fontenc}`, the header title changes from `First Last — Title` to `First Last | Title`.

**Expected Behavior**
The expected behavior is unknown; clarification is needed.

**Actual Behavior**
Importing the `fontenc` package with the `T1` option changes the title format from `First Last — Title` to `First Last | Title`.

**Minimum Working Example to Reproduce the Problem**
With `fontenc` - [Resume - with fontenc.pdf](https://github.com/user-attachments/files/15523859/Resume.-.with.fontenc.pdf):
```tex
\documentclass{moderncv}

\usepackage[T1]{fontenc}

\moderncvstyle{banking}

\name{John}{Smith}
\title{Software Engineer}


\begin{document}
    \maketitle
\end{document}
```

Without `fontenc` - [Resume - without fontenc.pdf](https://github.com/user-attachments/files/15523860/Resume.-.without.fontenc.pdf):
```tex
\documentclass{moderncv}

\usepackage[T1]{fontenc}

\moderncvstyle{banking}

\name{John}{Smith}
\title{Software Engineer}


\begin{document}
    \maketitle
\end{document}
```

**Specifications**
  - moderncv version and source: v2.3.1
  - LaTeX compiler (pdfLaTeX, XeLaTeX, etc.) and version: Latexmk, v4.83 | pdfTeX Version 3.141592653-2.6-1.40.26 (TeX Live 2024)
  - Platform (operating system, LaTeX editor, etc.): MacOS (Ventura 13.3.1 (a) | 22E772610a), VSCode 1.89.1 (Universal)

**Additional context**
None

**Comment by LLdaniel** [comment]
Hi @EvilCheetah, 

### Test
at first glance I did a short test with your MWE that lead me to the following result (Debian 12, LuaHBTeX, Version 1.15.0, pdfTeX 3.141592653-2.6-1.40.24):
| Revision | `\input[T1]{fontenc}` | Compiler | Result in `.pdf` |
|--------|--------|--------|--------|
|72603c4 (master)| yes | pdflatex | `\|` |
|72603c4 (master)| no | pdflatex | `\|` | 
|72603c4 (master)| yes | lualatex | `\|` |
|72603c4 (master)| no | lualatex | `\|` | 
|||||
|ab7c92f (2.3.1)|yes | pdflatex | `\|` |
|ab7c92f (2.3.1)|no | pdflatex | `-` |
|ab7c92f (2.3.1)|yes | lualatex | `\|` |
|ab7c92f (2.3.1)|no | lualatex | `\|` |

So this confirms your observation for 2.3.1 although the line in `moderncvheadiii.sty` is the same for both revisions:
```latex
\ifthenelse{\equal{\@title}{}}{}{\titlestyle{~|~\@title}}%
```
### Further progress of the issue
This needs a deeper investigation to understand the behaviour in version 2.3.1

### Request
Would you mind trying to compile the current master with you MWE and `pdflatex`? Maybe you can confirm my finding that the separator is consistently a `|` in a newer version of `moderncv`? 

### Opinion on what is right
Looking into the code I would say the intention was to use `|` as a separator. Also this separator is created consistently when using one of the recommended compilers (`lualatex` in this case).

**Comment by LLdaniel** [comment]
Now I could not let go that topic and did a deeper code investigation.
### Deeper Analysis
Looking into an encoding table like this [encguide.pdf](https://www.latex-project.org/help/documentation/encguide.pdf) reveals that the encoding of `\` in T1 (page 22) corresponds to `-` when using OT1 (page 19).

So my explanation is the following: 
When omitting `\input[T1]{fontenc}` OT1 is used and leads to `-`. Therefore the different behaviour in 2.3.1.
This can be seen when studying the `.log` files with and without setting the fontenc:
```diff
diff -u iss190.log iss190.log_wo 
--- iss190.log	2024-06-04 23:12:06.695562860 +0200
+++ iss190.log_wo	2024-06-04 23:11:21.015725078 +0200
@@ -334,10 +331,10 @@
 \pgf@yy=\dimen171
 \pgf@zx=\dimen172
 \pgf@zy=\dimen173
-LaTeX Font Info:    Trying to load font information for T1+qpl on input line 92
-6.
- (/usr/share/texmf/tex/latex/tex-gyre/t1qpl.fd
-File: t1qpl.fd 2009/09/25 v1.2 font definition file for T1/qpl
+LaTeX Font Info:    Trying to load font information for OT1+qpl on input line 9
+26.
+ (/usr/share/texmf/tex/latex/tex-gyre/ot1qpl.fd
+File: ot1qpl.fd 2009/09/25 v1.2 font definition file for OT1/qpl
```

When looking into the current master things get a bit different. Due to the change between these two commits
```diff
git diff 853e2164 fa3ebb6b -- moderncv.cls
diff --git a/moderncv.cls b/moderncv.cls
index 7c76e2a..06df7d7 100644
--- a/moderncv.cls
+++ b/moderncv.cls
@@ -120,6 +120,11 @@
     pdfsubject    = {R\'{e}sum\'{e} of \@firstname{}~\@lastname{}},
     pdfkeywords   = {\@firstname{}~\@lastname{}, curriculum vit\ae{}, r\'{e}sum\'{e}}}}
 
+% pdftex not using pdfmanagement-testphase requires T1 font encoding in order to handle links containing special characters somewhat properly
+\ifpdftex
+  \IfPDFManagementActiveTF{}{\RequirePackage[T1]{fontenc}}
+\fi
+
```
it is not really possible to omit `\input[T1]{fontenc}` anymore. This is why in newer version than fa3ebb6b the `-` is not shown anymore, because the fontenc T1 is called implicitly. 

Simply comment out these lines and you will get your `-` again without fontenc:
https://github.com/moderncv/moderncv/blob/72603c495e863b31dae9625753bcef355da3a1ea/moderncv.cls#L124-L126
### Conclusion
From my analysis I would say, yes, this is an issue in version 2.3.1, but this will be fixed implicitly in a newer release. Therefore I would expect that everything is fine with the newer code now. 
I hope this helps to clarify the topic for you a bit, @EvilCheetah. Please feel free to let me know what you think.

**Comment by EvilCheetah** [comment]
Thank you very much for clarification! I really appreciate your help!
