### ISSUE TITLE
Social links (and maybe others, too) break when including special characters)

### ISSUE THREAD

**Issue by mefuller** [moderncv/moderncv#99]
Per https://github.com/moderncv/moderncv/pull/97#issuecomment-1011505145 and https://github.com/moderncv/moderncv/pull/97#issuecomment-1011951248:

The links generated are completely broken with special characters: \social[twitter]{shadowmitia} gives https://twitter.com/shadowmitia \social[twitter]{jdoe\_doé\"o} gives https://twitter.com/jdoe_do\Uffffffff
Different sets of special characters seem to give the same result each time.

Stackoverflow allows special characters in usernames, which would break any social link pointing to a profile. 
I'm guessing more websites allow more than just ASCII.
I'm guessing we would have issues with other alphabets (I'm thinking Asia alphabets, but Cyrillic would probably cause issues too, and so would others).

**Comment by ingemarberg** [comment]
I've been looking at this issue and noticed a few interesting things. First of all, it seems to be somewhat dependent on the PDF reader if the links are broken or not. Okular seems to be having a hard time with some URLs generated by pdflatex, while both SumatraPDF running in Wine and Firefox (pdf.js) seem more forgiving. When using lualatex instead, the links work in all three PDF readers. It would probably be a good idea to use URL encoding in order to avoid this altogether. Fortunately, the new PDF management introduced in `pdfmanagement-testphase` makes this possible. In this case the URLs generated by pdflatex work even in Okular.

&nbsp; | Firefox (pdf.js) | Okular | SumatraPDF
---|---|---|---
pdflatex | ✅ |  ❌ | ✅
pdflatex with `pdfmanagement-testphase` | ✅ | ✅ | ✅
lualatex | ✅ | ✅ | ✅
lualatex with `pdfmanagement-testphase` | ✅ | ✅ | ✅

If you think this is the right way to tackle this, I would gladly submit a pull request. Here is what I've been using to test this so far. I've made the same changes to `\link` and `\httplink` as well, but for the sake of brevity they are not included below.

```
% makes an https hyperlink
% usage: \httpslink[optional text]{link}
\NewDocumentCommand{\httpslink}{O{}m}{%
  \IfPDFManagementActiveTF{%
    \ifthenelse{\equal{#1}{}}%
      {\hrefurl[urlencode]{https://#2}{#2}}%
      {\hrefurl[urlencode]{https://#2}{#1}}}{%
    \ifthenelse{\equal{#1}{}}%
      {\href{https://#2}{#2}}%
      {\href{https://#2}{#1}}}}
```

```
% uncomment this to use the new pdf management
\RequirePackage{pdfmanagement-testphase}
\DocumentMetadata{}

\documentclass{moderncv}
\moderncvstyle{classic}

% pdftex not using new pdf management requires T1 font encoding in order to handle links containing special characters somewhat properly
\ifpdftex
 \IfPDFManagementActiveTF{}{\usepackage[T1]{fontenc}}
\fi

\name{John}{Doe}
\social[twitter]{jdoe\_doé\"o}

\begin{document}
\makecvtitle

\texttt{\textbackslash httpslink}
\httpslink[Skånetrafiken]{www.skånetrafiken.se/}
\httpslink{www.skånetrafiken.se/}

\texttt{\textbackslash httplink}
\httplink[Skånetrafiken]{www.skånetrafiken.se/}
\httplink{www.skånetrafiken.se/}

\texttt{\textbackslash link}
\link[Skånetrafiken]{https://www.skånetrafiken.se/}
\link{https://www.skånetrafiken.se/}

\texttt{\textbackslash link}
\link[Skånetrafiken]{http://www.skånetrafiken.se/}
\link{http://www.skånetrafiken.se/}

\end{document}
```

**Comment by mefuller** [comment]
Thanks @ingemarberg - I would be really happy to receive a PR on this as it's a bugaboo that I didn't think was going to get resolved short of an update to `hyperref`!
